### ISSUE TITLE
Allow inline runsettings arguments

### ISSUE THREAD

**Issue by Silv-1** [joaoopereira/dotnet-test-rerun#95]
`dotnet test` allows passing inline RunSettings as the last arguments on the command line after "-- "

https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test

That is missing in `test-rerun`. `test-rerun` only supports the `--settings` parameter for runsettings.

**Comment by ricardofslp** [comment]
Hi @Silv-1,

Thanks for creating this issue.
We will try to work on this during this week.

**Comment by ricardofslp** [comment]
@Silv-1 ,

When you see the need for other parameters let us know by opening the issue.
We don't currently support all the options from dotnet test only the ones identified as useful until now.

**Comment by Silv-1** [comment]
I saw the multiple loggers are already implemented, awesome! Just the commits seem to have referenced #95 instead of #96 in the message.

**Comment by ricardofslp** [comment]
I will fix that as well as this issue soon.
Sorry been unable to pick it up in between.

**Comment by ricardofslp** [comment]
Already opened the PR for this.

Could you please test both issues with this alpha version: https://www.nuget.org/packages/dotnet-test-rerun/1.8.0-alpha.1 

Let us know the outcome.

**Comment by Silv-1** [comment]
I have issues with the runsettings parameters

Executing something similar to this

```
test-rerun /path/to/Solution.sln --configuration Release --logger trx -
-filter TestCategory=TestSuite_Suite1 --rerunMaxAttempts 1 -- MSTest.Parallelize.Workers=4
```

returns error 

```
Unrecognized command or argument 'MSTest.Parallelize.Workers=4'
```

**Comment by dgkanatsios** [comment]
thanks for the great library! +1 vote from me on adding support for RunSettings parameter.

**Comment by ricardofslp** [comment]
@Silv-1 will check why that is not working.

Thanks for the feedback.

**Comment by ricardofslp** [comment]
Hi @Silv-1 ,

The problem was that the library we are using don't recognize that command in order to have some control we've added a new input called --inlineRunSettings.
After adding that and separated by spaces each configuration you can add the input that you wanted.

So using as example -- MSTest.Parallelize.Workers=4 that would be called with --inlineRunSettings MSTest.Parallelize.Workers=4 which will then called dotnet test in the right way.

Please test with this version: https://www.nuget.org/packages/dotnet-test-rerun/1.8.0-alpha.2

**Comment by Silv-1** [comment]
Multiple `--logger` arguments and multiple `--inlineRunSettings` arguments work like a charm. 

Tested https://www.nuget.org/packages/dotnet-test-rerun/1.8.0-alpha.2.

Thank you very much. 🙏

**Comment by ricardofslp** [comment]
Released this officially in version https://www.nuget.org/packages/dotnet-test-rerun/1.8.0
Please test and close the issue if everything is as expected

**Comment by ricardofslp** [comment]
Hi @DavidAllardyce,

Yes, it is exactly that. It will show in the unparsed tokens and because of a configuration we've activated it will throw an error.

The feedback provided by that configuration adds good value as feedback. So we thought it would add more value to name the configuration but support the same behaviour by doing a map to what is done in dotnet test.

Regarding the tool thanks for the feedback.

**Comment by ricardofslp** [comment]
Hi @Silv-1 ,

Is it ok to close the two issues?

**Comment by dgkanatsios** [comment]
@ricardofslp inline run settings worked for us, thanks!

**Comment by Silv-1** [comment]
Works in the official release.

Tested https://www.nuget.org/packages/dotnet-test-rerun/1.8.0.
